#!/usr/bin/env python3
"""Merge all word JSON files into a single words-data.js file."""

import json
import os

BASE_DIR = os.getcwd()

GRADE_FILES = [
    ("grade7a.json", "七年级", "上册"),
    ("grade7b.json", "七年级", "下册"),
    ("grade8a.json", "八年级", "上册"),
    ("grade8b.json", "八年级", "下册"),
    ("grade9.json", "九年级", "全一册"),
]

def load_grade_data():
    """Load all grade JSON files and flatten into a single list."""
    grades = []
    all_words = []

    for filename, grade_name, volume_name in GRADE_FILES:
        filepath = os.path.join(BASE_DIR, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)

        grade_entry = {
            "grade": grade_name,
            "volume": volume_name,
            "units": []
        }

        for unit_data in data.get("units", []):
            unit_entry = {
                "unit": unit_data["unit"],
                "words": []
            }
            for word in unit_data.get("words", []):
                word_obj = {
                    "id": f"{grade_name}-{volume_name}-{unit_data['unit']}-{word['english']}",
                    "english": word["english"],
                    "chinese": word["chinese"],
                    "partOfSpeech": word.get("partOfSpeech", ""),
                    "grade": grade_name,
                    "volume": volume_name,
                    "unit": unit_data["unit"],
                }
                unit_entry["words"].append(word_obj)
                all_words.append(word_obj)

            grade_entry["units"].append(unit_entry)

        grades.append(grade_entry)

    return grades, all_words


def load_confusing_words():
    """Load confusing words data."""
    filepath = os.path.join(BASE_DIR, "confusingWords.json")
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def main():
    grades, all_words = load_grade_data()
    confusing = load_confusing_words()

    # Build confusing word groups for display
    confusing_groups = []
    for headword, similars in confusing.items():
        confusing_groups.append({
            "headword": headword,
            "similars": similars
        })

    output = [
        "// Auto-generated by build-data.py — do not edit by hand",
        "// All junior high school English vocabulary data",
        "const WORD_DATA = {",
    ]

    # Grades data (structured by grade → unit → words)
    output.append("  grades: " + json.dumps(grades, ensure_ascii=False, indent=2) + ",")

    # All words flat list (for easy iteration)
    output.append("  allWords: " + json.dumps(all_words, ensure_ascii=False, indent=2) + ",")

    # Confusing words groups
    output.append("  confusingGroups: " + json.dumps(confusing_groups, ensure_ascii=False, indent=2) + ",")

    # Metadata
    output.append("  meta: {")
    output.append(f"    totalWords: {len(all_words)},")
    output.append(f"    totalConfusingGroups: {len(confusing_groups)},")
    output.append("    grades: ['七年级', '八年级', '九年级'],")
    unique_pos = sorted(set(w['partOfSpeech'] for w in all_words))
    output.append("    partsOfSpeech: " + json.dumps(unique_pos, ensure_ascii=False) + ",")
    output.append("  },")
    output.append("};")

    out_path = os.path.join(BASE_DIR, "words-data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output))

    print(f"Generated words-data.js")
    print(f"   Total words: {len(all_words)}")
    print(f"   Grades: {len(grades)}")
    print(f"   Confusing groups: {len(confusing_groups)}")


if __name__ == "__main__":
    main()
